  name: CD_Workflow_actions_docker
  
  on:
    workflow_dispatch:
      
  jobs:
    build:
      uses: .github/workflows/reusable-node-build.yaml
      with:
        node-version: 16
        working-directory: ./hangman-api
        artifact-name: build-code

    delivery:
      runs-on: ubuntu-latest
      needs: build
      env:
        TAG: ${{ github.run_number }}-${{ github.run_id }} # o usa `date +%s` con otro step
      steps:
        - name: Checkout-build
          uses: actions/checkout@v4   
        - name: Download Artifact (carpeta dist)
          uses: actions/download-artifact@v4
          with: 
            name: build-code
            path: hangman-api/dist/
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: ./hangman-api
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/hangman-api-2025:${{ env.TAG }}
            file: ./hangman-api/Dockerfile.workflow
            