name: CD_Workflow

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [main]
    paths: ["hangman-api/**"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:                                
    - name: Checkout-build
      uses: actions/checkout@v4           
    - name: Setup Node.js node-version
      uses: actions/setup-node@v4       
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: hangman-api/package-lock.json
    - name: build
      working-directory: ./hangman-api
      run: |
        npm ci                           
        npm run build --if-present
    - name: Upload Artifact (carpeta dist)
      uses: actions/upload-artifact@v4
      with: 
        name: build-code
        path: hangman-api/dist/
  delivery:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout-build
        uses: actions/checkout@v4   
      - name: Download Artifact (carpeta dist)
        uses: actions/download-artifact@v4
        with: 
          name: build-code
          path: hangman-api/dist/
      - name: build docker image
        working-directory: ./hangman-api
        run: docker build -t hangman-api:latest -f Dockerfile.workflow .