  name: CD_Workflow

  on:
    push:
    pull_request:
      branches: [main]
      paths: ["hangman-api/**"]
    workflow_dispatch:
      
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:                                
      - name: Checkout-build
        uses: actions/checkout@v4           
      - name: Setup Node.js node-version
        uses: actions/setup-node@v4       
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: hangman-api/package-lock.json
      - name: build
        working-directory: ./hangman-api
        run: |
          npm ci                           
          npm run build --if-present
      - name: Upload Artifact (carpeta dist)
        uses: actions/upload-artifact@v4
        with: 
          name: build-code
          path: hangman-api/dist/ # guardar la carpeta hangman-api/dist/ (resultado del build) para que pueda ser descargada en otro job.
    delivery:
      runs-on: ubuntu-latest
      needs: build
      env:
        TAG: ${{ github.run_number }}-${{ github.run_id }} # o usa `date +%s` con otro step
      steps:
        - name: Checkout-build
          uses: actions/checkout@v4   
        - name: Download Artifact (carpeta dist)
          uses: actions/download-artifact@v4
          with: 
            name: build-code
            path: hangman-api/dist/
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: ./hangman-api
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/hangman-api-2025::${{ env.TAG }}
            file: Dockerfile.workflow