name: CI                    # Nombre del workflow. Aparecerá como "CI" en la pestaña Actions de GitHub.

on:                         # Definición de eventos que disparan la ejecución del workflow.
  push:
    branches: [main]        # El workflow se ejecutará cuando haya un push a la rama main.
  pull_request:
    branches: [main]        # También se ejecutará cuando se cree o actualice un pull request hacia la rama main.

jobs:                       # Definición de los jobs (tareas) que componen el workflow.
  audit:                    # Nombre del job. Puede ser cualquier nombre identificativo.
    runs-on: ubuntu-latest  # Indica que el job se ejecutará en una máquina virtual Ubuntu (última versión disponible).

    steps:                          # Lista de pasos que se ejecutarán dentro del job.
    - uses: actions/checkout@v4     # Este paso utiliza la acción oficial "checkout" para clonar el código del repositorio.
      name: Checkout
    - name: Inspect machine         # Nombre descriptivo del paso. Se verá en el log del workflow.
      run:  |                       # Indica que se ejecutarán varios comandos de shell.
        ls -al                      
        whoami
        pwd
        node -v