name: CI

on:
  push:
    branches: [main]
    paths: ["hangman-api/**"]
  pull_request:
    branches: [main]
    paths: ["hangman-api/**"]

jobs:
  build:   # primer job llamado build
    runs-on: ubuntu-latest
    steps:                                
    - name: Checkout-build
      uses: actions/checkout@v4           
    - name: Setup Node.js node-version
      uses: actions/setup-node@v4         
      with:
        node-version: 20
    - name: build
      working-directory: ./hangman-api
      run: |
        npm ci                           
        npm run build --if-present
    - name: Upload Artifact (dependencias)
      uses: actions/upload-artifact@v4
      with: 
        name: dependencias
        path: hangman-api/node_modules/
          

  test:   # segundo job llamado test
    needs: build  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout-test
      uses: actions/checkout@v4
    - name: Download Artifact (dependencias)
      uses: actions/download-artifact@v4
      with: 
        name: dependencias
        path: hangman-api/node_modules/
    - name: test
      working-directory: ./hangman-api
      run: | 
        ls -la
        npm test