  name: Reusable node build
  
  on:
    workflow_call:  
      inputs:
        node-version:
          required: true
          type: number
        working-directory:
          required: true
          type: string
        artifact-name:
          required: true
          type: string

  
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:                                
      - name: Checkout-build
        uses: actions/checkout@v4           
      - name: Setup Node.js node-version
        uses: actions/setup-node@v4       
        with:
          node-version: ${{ inputs.node.version}}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json
      - name: build
        working-directory: .${{ inputs.working-directory }}
        run: |
          npm ci                           
          npm run build --if-present
      - name: Upload Artifact (carpeta dist)
        uses: actions/upload-artifact@v4
        with: 
          artifact-name: ${{ inputs.artifact-name   }}
          path: ${{ inputs.working-directory }}/dist/
      